source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'QtQuick_Example', :exclusive => true do
  pod "QtQuick", :path => "../"
end

target 'QtQuick_Tests', :exclusive => true do
  pod "QtQuick", :path => "../"

  
end
